server:
  port: 8083

spring:
  application:
    name: account-microservice

  datasource:
    url: ${ACCOUNT_DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      schema: account_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS account_schema
      connection-timeout: 10000

  jpa:
    properties:
      hibernate:
        show_sql: false
        hbm2ddl:
          auto: none
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true

  cloud:
    function:
      definition: user;activity
    stream:
      kafka:
        binder:
          brokers: localhost:9093
          auto-create-topics: false

      bindings:
        user-in-0:
          destination: new-user
          content-type: application/json
          group: account-microservice-group
          consumer:
            start-offset: latest
            concurrency: 2
        activity-in-0:
          destination: activity
          content-type: application/json
          group: account-microservice-group
          consumer:
            start-offset: latest
            concurrency: 2
app:
  scheduled:
    interval-in-cron: "*/30 * * * * ?"
    cutoff-time: 2