services:

  postgres:
    image: postgres:17.2
    container_name: postgres-microservices
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - microservices

  redis:
    restart: always
    image: mirror.gcr.io/redis
    container_name: redis-microservices
    ports:
      - "6379:6379"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge