server:
  port: 9090

spring:
  application:
    name: gateway

app:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  headers:
    - Authorization
    - Content-Type

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka