server:
  port: 8761

spring:
  application:
    name: discovery

eureka:
  dashboard:
    path: /dashboard/
    enabled: true
  client:
    enabled: true
    register-with-eureka: false
    fetch-registry: false

    serviceUrl:
      defaultZone: http://localhost:8761/eureka/